// Flat ESLint config. Scoped to src/ (application TypeScript). Generated and
// build output is ignored. No formatter is enforced — ESLint catches substance
// (unused vars, prefer-const, useless escapes, etc.); house style stays manual.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'src/userGuideHtml.ts', // generated by scripts/build-user-guide.mjs
      'dist/',
      'site/',
      'node_modules/',
      'packages/parsers/pkg/',
      'src-tauri/',
      // Cargo/Tauri build output. This is a Cargo workspace, so it lands at the
      // repo root, NOT under src-tauri/ — ignoring src-tauri/ alone leaves
      // thousands of generated .js assets (tauri-codegen-assets) in scope, which
      // `npm run lint` only escapes because it is scoped to src/.
      'target/',
      // The docs-site Python virtualenv (zensical) — vendored JS assets.
      '.venv/',
      '**/*.bench.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSelectElement: 'readonly',
        ResizeObserver: 'readonly',
        Worker: 'readonly',
        self: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        FileReader: 'readonly',
        localStorage: 'readonly',
        setTimeout: 'readonly',
        requestAnimationFrame: 'readonly',
      },
    },
    rules: {
      // tsconfig already enforces noUnusedLocals/Parameters; keep ESLint's
      // version aligned and allow leading-underscore opt-outs.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
);
